version: '2.0'

# HELP :
#   start with "docker-compose build" to rebuild Dockerfiles if the images are not found.
#   start with "docker-compose up -d" to run in the background

services:
#00 ===================================================================================================================================================================================
  phpfpm_dividends_realtime:
    container_name: phpfpm_dividends_realtime
    image: phpfpm_image # you should load the phpfpm.docker image first
    build: ./phpfpm
    volumes:
      - ./phpfpm/project-files:/var/www/html:z
      - ./logs/php:/var/log/phpfpm-logs:z
    restart: always
#00 ===================================================================================================================================================================================
  apache_dividends_realtime:
      container_name: apache_dividends_realtime
      image: bitnami/apache:2.4.46-debian-10-r171
      ports:
          - "8080:8080"
          - "8443:8443"
      volumes:
          - ./phpfpm/project-files:/app:ro
          - ./apache/vhosts:/opt/bitnami/apache/conf/vhosts:ro
          - ./apache/conf/httpd.conf:/opt/bitnami/apache/conf/httpd.conf:ro
          - ./logs/apache:/var/log/apache2:z
      depends_on:
          - phpfpm_dividends_realtime # loads phpfpm before nginx to make host [phpfpm] available
      restart: always
#00 ===================================================================================================================================================================================
# available shared networks, make nginx access phpfpm with [ping phpfpm] hostname.
networks:
  default:
    external:
      name: ghostlexly-network
